<!DOCTYPE html>
<html class="<?php print $class; ?>">
<head>
	<title><?php print $title; ?></title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	
	<?php if(isset($meta) && is_array($meta)): ?>
    <?php foreach($meta as $name => $content): ?>
    <meta name="<?php print $name; ?>" content="<?php print $content; ?>" />
    <?php endforeach; ?>
    <?php endif; ?>
    <link rel="icon" href="images\favicon.ico" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="styles\style.css">
	<link rel="stylesheet" type="text/css" href="styles\bootstrap\css\bootstrap.css">
	<link rel="stylesheet" type="text/css" href="styles\slick-master\css\style.css"/>
	<link rel="stylesheet" type="text/css" href="styles\jquery.fullPage.css"/>
	<script type="text/javascript" src="scripts\jquery-2.1.1.min.js"></script>
	<script type="text/javascript" src="jquery-ui-1.11.1\jquery-ui.min.js"></script>
	<script type="text/javascript" src="styles\jquery.fullPage.js"></script>
	<script type="text/javascript" src="styles\jquery.fullPage.min.js"></script>
	<script type="text/javascript" src="styles\slick-master\slick-master\js\scripts.js"></script>
	<script type="text/javascript" src="\styles\bootstrap\js\bootstrap.js"></script>
</head>
<body>
	<div>
		<div class="head"><?php echo $head; ?></div>
		<div class="body"><?php echo $body; ?></div>
		<div class="foot"><?php echo $foot; ?></div>
    </div>
</body>
</html>