<div class="nav-fixed-horizontal fc">
	<center>
		<a href="admin" role="button" class="btn btn-info btn-sm "><span class="glyphicon glyphicon-arrow-left"></span> Back</a></br></br>
		<a href="?logout=1" role="button" class="btn btn-info btn-sm "><span class="glyphicon glyphicon-off"></span>Log Out</a></br>
	</center>
</br>
	<ul class="nav nav-pills">
		<li><a href="branch">List of Projects</a></li>
		<li><a href="messages">Messages</a></li>
		<li class="notif" style="background-color:<?php echo isset($unviewed)?'red':'transparent';?>">
			<a href="requests">Request Notifications</a>
		</li>
		<li><a href="addproject">Add Projects</a></li>
		<li><a href="portfolio">Portfolio</a></li>
	</ul>
</div>
<div class="container col-sm-offset-2">
	<div class="container2">
		<div class="row">
			<div class="col-xs-12 col-md-8">
				<h2 class="pull-left" style="font-family:monospace;"> Welcome Admin!</h2>
			</div>
		</div>
		<div class="row col-sm-9 col-sm-offset-2">
				<h3>Add a project</h3>
				<div class=" col-sm-8 ">
					<form method="POST">
						<input class="form-control pull-right" type="text" name="name" placeholder="Project name" required/></br></br>
						<select name="type" class="form-control">
							<option value="Tarpaulin">Tarpaulin</option>
							<option value="Signboard Sticker with angle bar frame">Signboard Sticker with angle bar frame</option>
							<option value="Mural Sintra Board Sticker">Mural Sintra Board Sticker</option>
							<option value="Sticker">Sticker</option>
							<option value="T-shirt">T-shirt</option>
						</select></br>
						<div class="height col-sm-4 col-sm-offset-2">
							<h5>Height:</h5>
							<input type="number" class="form-control " name="height" min="1"/>
							<h5>Width:</h5>
							<input type="number" class="form-control " name="width" min="1"/>
						</div>
						<div class="quantity col-sm-4 col-sm-offset-2">
							<h5>Quantity:</h5>
							<input type="number" class="form-control " name="quantity" min="1"/>
						</div>
						<div class="face col-sm-4 col-sm-offset-2">
							<h5>Face:</h5>
							<input class="form-control pull-right" type="text" name="face" placeholder="type"/></br></br>
						</div>
						<button class="pull-right btn btn-lg btn-info" type="submit">Add</button>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	$(document).ready(function() {
		$(".quantity").hide();
		$(".face").hide();
		$(".type").hide();
	});
	$("select").on("change", function(){
		$(".quantity").hide();
		$(".height").hide();
		$(".face").hide();
		$(".type").hide();
		if ($(this).val() == "T-shirt") {
			$(".quantity").show();
		}
		else if ($(this).val() == "Sticker") {
			$(".height").show();
			$(".face").show();
		}
		else {
			$(".height").show();
		}
	});

</script>