<div class="nav-fixed-horizontal fc">
	<center>
		<a href="admin" role="button" class="btn btn-info btn-sm "><span class="glyphicon glyphicon-arrow-left"></span>Back</a></br></br>
		<a href="?logout=1" role="button" class="btn btn-info btn-sm "><span class="glyphicon glyphicon-off"></span>Log Out</a></br>
	</center>
</br>
	<ul class="nav nav-pills">
		<li><a href="messages">List of Projects</a></li>
		<li><a href="messages">Messages</a></li>
		<li class="notif" style="background-color:<?php echo isset($unviewed)?'red':'transparent';?>">
			<a href="requests">Request Notifications</a>
		</li>
		<li><a href="addproject">Add Projects</a></li>
	</ul>
</div>
	<div class="container col-sm-offset-2">
	<div class="container2">
		<div class="row">
			<div class="col-xs-12 col-md-8">
				<h2 class="pull-left" style="font-family:monospace;"> Welcome Admin!</h2>
			</div>
		</div>
		<div class="row col-sm-9 col-sm-offset-1">
				<div class=" col-sm-8">
					<h3>Add a project</h3>
					<input class="form-control pull-right" type="text" name="project" placeholder="Project name" required/></br></br>
					<button class="pull-right btn btn-info" type="submit">Add</button>
				</div>
			</div>
		</div>
	</div>
</div>