<div>
	<div class="clearfix" style="position:fixed;z-index:70;height:70px;width:100%;background-color:black;">
		<h1 class="pull-left header-name">Hi Admin</h1>
	
	</div>
	<div style="position:fixed;z-index:70;height:100%;width:20em;background-color:grey;margin-top:70px">
		<ul class="project">
			<li><a href="#" style="text-decoration:none;color:black">List of Projects</a></li>
			<li><a href="#" style="text-decoration:none;color:black">Messages</a></lu>
			<li><a href="a" style="text-decoration:none;color:black">Request Notif</a></li>
			<li><a href="#" style="text-decoration:none; color:black">Add Project</a></li>
		</ul>
	</div>
	<div class="col-sm-offset-3" style="position:fixed;height:40em;width:60em;background-color:grey;margin-top:6em;border-radius:10px;">
		<h1 class="header-code"><strong>Code:</strong></h1>
		<div style="position:fixed;height:10em;width:60em;background-color:grey">
			<h1 class="header-project2"><strong>Project Name</strong></h1>
			<div style="height:60px;width:500px;margin-left:10em">
				<div class="progress">
 				 	<div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 30%;">
    				40%
  					</div>
  				</div>
  				<div style="height:20px;width:30%;">
  					<p style="float:right;font-size:20px">
  						<strong>xx/xx/xx</strong>
  					</p>
  				</div>
	  			<div style="height:20px;width:100%">
	  				<p>
	  					<strong class="pull-left">xx/xx/xx</strong><strong class="pull-right">xx/xx/xx</strong>
	  				</p>
  				</div>
  				<br/>
  				<select class="pull-right">
					<option>10%</option>
					<option>20%</option>
					<option>30%</option>
					<option>40%</option>
					<option>50%</option>
					<option>60%</option>
					<option>70%</option>
					<option>80%</option>
					<option>90%</option>
					<option>100%</option>
				</select>
			</div>
		<div style="position:fixed;height:10em;width:60em;background-color:grey;margin-top:5em">
			<div style="height:10em;width:50em;background-color:black;margin-left:5em;">
				<p style="color:white;margin-left:10px;padding-top:10px">
					<strong>
					Tarpaulin: 40 x 50 = 15000 <br/>
					Streamer:  50 x 50 = 10000
					</strong>
				</p>
				<p style="color:white; text-align:right;margin-right:10px">
					<strong>
					Total:25000
					</strong>
				</p>
			</div>
			<button class="button pull-right" style="margin-right:70px">Edit</button>
		</div>
		<div style="position:fixed;height:10em;width:60em;background-color:grey;margin-top:22em">
			<button class="button"><strong>Message</strong></button>
			<button class="button"><strong>Gallery</strong></button>
		</div>

	
	</div>


</div>