<div class="nav-fixed-horizontal fc">
	<center>
		<a href="admin" role="button" class="btn btn-info btn-sm "><span class="glyphicon glyphicon-arrow-left"></span> Back</a></br></br>
		<a href="?logout=1" role="button" class="btn btn-info btn-sm "><span class="glyphicon glyphicon-off"></span>Log Out</a></br>
	</center>
</br>
	<ul class="nav nav-pills">
		<li><a href="branch">List of Projects</a></li>
		<li><a href="messages">Messages</a></li>
		<li class="notif" style="background-color:<?php echo isset($unviewed)?'red':'transparent';?>">
			<a href="requests">Request Notifications</a>
		</li>
		<li><a href="addproject">Add Projects</a></li>
		<li><a href="admingal">Gallery</a></li>
		<li><a href="portfolio">Portfolio</a></li>
	</ul>
</div>
<div class="container col-sm-offset-2">
	<div class="container2">
		<div class="row">
			<div class="col-xs-12 col-md-8">
				<h2 class="pull-left" style="font-family:monospace;"> Welcome Admin!</h2>
			</div>
		</div>
		<div class="row col-sm-10 col-sm-offset-1">
				<h2>Projects</h2>
				<div class="row">
						<div class="col-sm-offset-3" style="position:fixed;height:40em;width:60em;background-color:grey;margin-top:6em;border-radius:10px;">
		<h1 class="header-code"><strong>Code:</strong></h1>
		<div style="position:fixed;height:10em;width:60em;background-color:grey">
			<h1 class="header-project2"><strong>Project Name</strong></h1>
			<div style="height:60px;width:500px;margin-left:10em">
				<div class="progress">
 				 	<div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 30%;">
    				40%
  					</div>
  				</div>
  				<div style="height:20px;width:30%;">
  					<p style="float:right;font-size:20px">
  						<strong>xx/xx/xx</strong>
  					</p>
  				</div>
	  			<div style="height:20px;width:100%">
	  				<p>
	  					<strong class="pull-left">xx/xx/xx</strong><strong class="pull-right">xx/xx/xx</strong>
	  				</p>
  				</div>
  				<br/>
  				<select class="pull-right">
					<option>10%</option>
					<option>20%</option>
					<option>30%</option>
					<option>40%</option>
					<option>50%</option>
					<option>60%</option>
					<option>70%</option>
					<option>80%</option>
					<option>90%</option>
					<option>100%</option>
				</select>
			</div>
		<div style="position:fixed;height:10em;width:60em;background-color:grey;margin-top:5em">
			<div style="height:10em;width:50em;background-color:black;margin-left:5em;">
				<p style="color:white;margin-left:10px;padding-top:10px">
					<strong>
					Tarpaulin: 40 x 50 = 15000 <br/>
					Streamer:  50 x 50 = 10000
					</strong>
				</p>
				<p style="color:white; text-align:right;margin-right:10px">
					<strong>
					Total:25000
					</strong>
				</p>
			</div>
		</div>
		<div style="position:fixed;height:10em;width:60em;background-color:grey;margin-top:22em">
			<button class="button"><strong>Message</strong></button>
			<button class="button"><strong>Gallery</strong></button>
		</div>
	</div>
</div>
				</div>
			</div>
		</div>
	</div>
</div>
	