<div class="nav-fixed-horizontal fc">
	<center>
		<a href="?logout=1" role="button" class="btn btn-info btn-sm"><span class="glyphicon glyphicon-off"></span>Log Out</a></br>
	</center>
	<h4>List</h4>
	<div class="list-box">
			<ul>
				<li>
					Branch
					<ul>
						<li name="3">
							Project
						</li>
						<li>
							Project
						</li>
						<li>
							Project
						</li>
					</ul>
				</li>
			</ul>
	</div>
	<ul class="nav nav-pills">
		<li><a href="branch">List of Projects</a></li>
		<li><a href="messages">Messages</a></li>
		<li class="notif" style="background-color:<?php echo isset($unviewed)?'red':'transparent';?>">
			<a href="requests">Request Notifications</a>
		</li>
		<li><a href="addproject">Add Projects</a></li>
		<li><a href="portfolio">Portfolio</a></li>
	</ul>
</div>
<div style="background-color:cyan;">

</div>
<script type="text/javascript">
	$("li").on("click", function() {
		if ($(this).children("ul").css("display") == "none") {
			$(this).children("ul").show();
		}
		else {
			$(this).children("ul").hide();
		}
	});
	$(".notif").on("click", function() {
		$.ajax({
          url: "admin",
          type: "POST",
          data: {"setviewed":1}
        });
	});
</script>