<div>
	<div class="clearfix" style="position:fixed;z-index:70;height:70px;width:100%;background-color:black;">
		<h1 class="pull-left header-name">Hi Admin</h1>
	
	</div>
	<div style="position:fixed;z-index:70;height:100%;width:20em;background-color:grey;margin-top:70px">
		<ul class="project">
			<li>List of Projects</li>
			<li>Messages</lu>
			<li>Request Notif</li>
			<li>Add Project</li>
		</ul>
	</div>
	<div class="col-sm-offset-3" style="position:fixed;height:40em;width:60em;background-color:grey;margin-top:6em;border-radius:10px;">
		<h1 class="header-code"><strong>Code:</strong></h1>
		<div style="position:fixed;height:10em;width:60em;background-color:green">
			<h1 class="header-project2"><strong>Project Name</strong></h1>
		</div>
		<div style="position:fixed;height:10em;width:60em;background-color:yellow;margin-top:12em">
		</div>
		<div style="position:fixed;height:10em;width:60em;background-color:red;margin-top:24em">
			<button class="button"><strong>Message</strong></button>
			<button class="button"><strong>Gallery</strong></button>
		</div>

	
	</div>


</div>