<div>
	<div class="clearfix" style="position:fixed;z-index:70;height:70px;width:100%;background-color:black;">
		<h1 class="pull-left header-name">Hi Admin</h1>
	
	</div>
	<div style="position:fixed;z-index:70;height:100%;width:20em;background-color:grey;margin-top:70px">
		<ul class="project">
			<li>List of Projects</li>
			<li>Messages</lu>
			<li>Request Notif</li>
			<li>Add Project</li>
		</ul>
	</div>
	<div class="col-sm-offset-3" style="position:fixed;height:40em;width:60em;background-color:grey;margin-top:6em;border-radius:10px;">
			<h1>Gallery</h1>
			<button class="pull-right button-upload1" style="margin-right:30px">Upload</button>
			<div style="position:float;height:25em;width:50em;background-color:#fff;margin-left:5em;margin-top:9em">
			</div>

	</div>
</div>