<ul id="menu" class="nav nav­pills nav-justified nav-fixed">
		<li data-menuanchor="home" class="active"><a href="#home"><img class="logo" src="images\logobnw1.png"/></a></li>
		<li><a href="gallery">Gallery</a></li>
		<li><a href="customer">Messages</a></li>
		<li><a href="billing">Billing</a></li>
		<li><button class="btn btn-info">Notifications</button></a>
		</li>
		<li><a href="?logout=1" role="button" class="btn btn-info"><span class="glyphicon glyphicon-off"></span></a></li>
		<li></li>
</ul>\
<div class="container">
	<div class="container2">
		<div class="row">
			<div class="col-xs-12 col-md-8">
				<h2 class="pull-left" style="font-family:monospace;"> Welcome User!</h2>
			</div>
		</div>
		<div class="row col-sm-11">
				<center><h3>Billing</h3></center>
				<div class="row col-sm-8 col-sm-offset-2 fc proj-border">
					<p >
					<strong>
						Project 1
					</strong>
					<br/>
					<strong>
					Tarpaulin: 40 x 50 = 15000 <br/>
					Streamer:  50 x 50 = 10000
					</strong>
					</p>
					<p class="pull-right">
						<strong>
						Total:25000
						</strong>
					</p>
				</div>
				<div class="row col-sm-8 col-sm-offset-2 fc proj-border">
					<p >
					<strong>
						Project 1
					</strong>
					<br/>
					<strong>
					Tarpaulin: 40 x 50 = 15000 <br/>
					Streamer:  50 x 50 = 10000
					</strong>
					</p>
					<p class="pull-right">
						<strong>
						Total:25000
						</strong>
					</p>
				</div>

			</div>
	</div>
</div>

