<div>
	<div class="clearfix" style="position:fixed;z-index:70;height:70px;width:100%;background-color:black;">
		<h1 class="pull-left header-name">Hi "NAME"</h1>
		<ul class="nav-bar2">
			<li>Projects</li>
			<li>Gallery</li>
			<li>Messages</li>
			<li>Billing</li>
		</ul>
	</div>
	<div class="clearfix" style="width:100%; height:800px;">
		<br/>
		<br/>
		<br/>
		<br/>
		<div style="width:80%; height:150px; background-color:red;">
		</div>
		<div style="width:80%; height:150px; background-color:yellow;">
		</div>
		<div style="width:80%; height:150px; background-color:red;">
		</div>
		<div style="width:80%; height:150px; background-color:yellow;">
		</div>
	</div>
</div>
