<div>
	<div class="clearfix" style="position:fixed;z-index:70;height:70px;width:100%;background-color:black;">
		<h1 class="pull-left header-name">Hi "NAME"</h1>
		<ul class="nav-bar2">
			<li>Projects</li>
			<li>Gallery</li>
			<li>Messages</li>
			<li>Billing</li>
		</ul>
	</div>
	<div class="clearfix" style="width:1000px; height:800px;margin-left:100px;">
		<br/>
		<br/>
		<br/>
		<br/>
		<div style="width:80%; height:150px; background-color:grey;">
			<div style="height:10em;width:50em;background-color:black;margin-left:5em;padding-top:10px">
				<p style="color:white;margin-left:10px;padding-top:10px">
					<strong>
						Project 1
					</strong>
					<br/>
					<strong>
					Tarpaulin: 40 x 50 = 15000 <br/>
					Streamer:  50 x 50 = 10000
					</strong>
				</p>
				<p style="color:white; text-align:right;margin-right:10px">
					<strong>
					Total:25000
					</strong>
				</p>
			</div>
		</div>
		<div style="width:80%; height:150px; background-color:grey;">
			<div style="height:10em;width:50em;background-color:black;margin-left:5em;">
				<p style="color:white;margin-left:10px;padding-top:10px">
					<strong>
						Project 2
					</strong>
					<br/>
					<strong>
					Tarpaulin: 40 x 50 = 15000 <br/>
					Streamer:  50 x 50 = 10000
					</strong>
				</p>
				<p style="color:white; text-align:right;margin-right:10px">
					<strong>
					Total:25000
					</strong>
				</p>
			</div>
		</div>
		<div style="width:80%; height:150px; background-color:grey;">
			<div style="height:10em;width:50em;background-color:black;margin-left:5em;">
				<p style="color:white;margin-left:10px;padding-top:10px">
					<strong>
						Project 3
					</strong>
					<br/>
					<strong>
					Tarpaulin: 40 x 50 = 15000 <br/>
					Streamer:  50 x 50 = 10000
					</strong>
				</p>
				<p style="color:white; text-align:right;margin-right:10px">
					<strong>
					Total:25000
					</strong>
				</p>
			</div>
		</div>
		<div style="width:80%; height:150px; background-color:grey;">
			<div style="height:10em;width:50em;background-color:black;margin-left:5em;">
				<p style="color:white;margin-left:10px;padding-top:10px">
					<strong>
						Project 4
					</strong>
					<br/>
					<strong>
					Tarpaulin: 40 x 50 = 15000 <br/>
					Streamer:  50 x 50 = 10000
					</strong>
				</p>
				<p style="color:white; text-align:right;margin-right:10px">
					<strong>
					Total:25000
					</strong>
				</p>
			</div>
		</div>
	</div>
</div>
