<div>
	<div class="clearfix" style="position:fixed;z-index:70;height:70px;width:100%;background-color:black;">
		<h1 class="pull-left header-name">Hi Admin</h1>
	
	</div>
	<div style="position:fixed;z-index:70;height:100%;width:20em;background-color:grey;margin-top:70px">
		<ul class="project">
			<li>List of Projects</li>
			<li>Messages</lu>
			<li>Request Notif</li>
			<li>Add Project</li>
		</ul>
	</div>
	<div class="col-sm-offset-3" style="position:fixed;height:40em;width:60em;background-color:grey;margin-top:6em;border-radius:10px;">
		<div class="pull-left"style="height:35em;width:26em;background-color:white;margin-top:2em;margin-left:2em">
			<div style="height:60px;width:100%;background-color:black">
				<p style="color:white;font-size:30px;padding-top:10px;text-align:center"><strong>Unfinished</strong></p>
			</div>
		</div>
		<div class="pull-right" style="height:35em;width:26em;background-color:white;margin-top:2em;margin-right:2em">
			<div style="height:60px;width:100%;background-color:black;">
				<p style="color:white;font-size:30px;padding-top:10px;text-align:center"><strong>Finished</strong></p>
			</div>
		</div>
	</div>
</div>