<div class="nav-fixed-horizontal fc">
	<center>
		<a href="admin" role="button" class="btn btn-info btn-sm "><span class="glyphicon glyphicon-arrow-left"></span> Back</a></br></br>
		<a href="?logout=1" role="button" class="btn btn-info btn-sm "><span class="glyphicon glyphicon-off"></span>Log Out</a></br>
	</center>
</br>
	<ul class="nav nav-pills">
		<li><a href="branch">List of Projects</a></li>
		<li><a href="messages">Messages</a></li>
		<li class="notif" style="background-color:<?php echo isset($unviewed)?'red':'transparent';?>">
			<a href="requests">Request Notifications</a>
		</li>
		<li><a href="addproject">Add Projects</a></li>
		<li><a href="admingal">Gallery</a></li>
		<li><a href="portfolio">Portfolio</a></li>
	</ul>
</div>
<div class="container col-sm-offset-2">
	<div class="container2">
		<div class="row">
			<div class="col-xs-12 col-md-8">
				<h2 class="pull-left" style="font-family:monospace;"> Welcome Admin!</h2>
			</div>
		</div>
		<div class="row col-sm-10 col-sm-offset-1">
				<h2>Projects</h2>
				<div class="row">
						<div class="col-sm-6">
							<div class="panel panel-default">
							  <div class="panel-heading">
							    <h3 class="panel-title">Unfinished</h3>
							  </div>
							  <div class="branch">
							    Panel content
							  </div>
							</div>
						</div>
						<div class="col-sm-6">
							<div class="panel panel-default">
							  <div class="panel-heading">
							    <h3 class="panel-title">Finished</h3>
							  </div>
							  <div class="branch">
							    Panel content
							  </div>
							</div>
						</div>
				</div>
			</div>
		</div>
	</div>
</div>