<a href="?logout=1">LOG OUT</a>
<div>
	<div class="clearfix" style="position:fixed;z-index:70;height:70px;width:100%;background-color:black;">
		<h1 class="pull-left header-name">Hi <?php echo $user['username'];?></h1>
		<ul class="nav-bar2">
			<li>Projects</li>
			<li>Gallery</li>
			<li>Messages</li>
			<li>Billing</li>
		</ul>
	</div>
	<div style="position:fixed;z-index:70;height:100%;width:20em;background-color:grey;margin-top:70px;">
		<ul class="project">
			<?php if (!empty($projects)){
				foreach ($projects as $key => $project) {
					echo '<li><a href="?code='.$project['code'].'">'.$project['code'].'</a></li>';
				}
			}
			else {
				echo '<li>You have no projects</li>';
			} 
			?>

		</ul>
	</div>
	<?php if (!empty($projects)): ?>
		<div class="msg-box col-sm-offset-3" style="position:fixed;height:30em;width:40em;background-color:grey;margin-top:8em;border-radius:10px;">
			<?php foreach($messages as $key => $message) {
						echo $message['username'].': '.$message['content'].'<br/>';
					}
			?>
		</div>
		<div class="col-sm-offset-3" style="position:fixed;height:80px;width:40em;background-color:grey;margin-top:41em;border-radius:10px;">
			<textarea></textarea>
			<button class="send">Send</button>
		</div>
	<?php endif; ?>
	<div class="col-sm-offset-9" style="position:fixed;height:39em;width:20em;background-color:#fff;margin-top:8em;border-radius:10px;">
		<div style="height:30em;width:20;background-color:grey;border-radius:10px">
		</div>
		<button style="border-radius:5px">Upload</button>
	</div>
</div>
<script type="text/javascript">
	var timestamp = null;
	var ajax = null;
	function comet() {
		ajax = $.ajax({
			type : 'Get',
			url  : 'read?timestamp=' + timestamp,
			async : true,
			cache : false,
			success : function(data) {
						var json = eval('(' + data + ')');
						if(json['msg'] == ''){
						}else { 
							$(".msg-box").append(json['msg']);
						}
						timestamp  = json['timestamp'];
						setTimeout('comet()', 1000);
			},
			error : function(XMLHttpRequest, textstatus, error) { 
						alert(error);
						setTimeout('comet()', 15000);
			}		
		});
	}
	$(function() {
		comet();
	});
	jQuery(function($) {
		$(".send").on("click", function() {
			ajax.abort();
			$.ajax({
				type: "POST",
				url: "customer",
				data: {code : "<?php echo $code; ?>", message : $(this).parent().children("textarea").val()}
			}).success(function(){
				$.ajax({
					type : 'GET',
					url  : 'write',
					async : true,
					cache : false
				}).success(function(data){
					comet();
				});
			});
			// $(".msg-box").append("<?php echo $user['username'].': ';?>"+$(this).parent().children("textarea").val()+"<br/>");
			$(this).parent().children("textarea").val("");
		});
	});
</script>