<div>
	<div class="clearfix" style="position:fixed;z-index:70;height:70px;width:100%;background-color:black;">
		<h1 class="pull-left header-name">Hi "NAME"</h1>
		<ul class="nav-bar2">
			<li>Projects</li>
			<li>Gallery</li>
			<li>Messages</li>
			<li>Billing</li>
		</ul>
	</div>
	<div class="clearfix" style="width:100%; height:800px;">
		<br/>
		<br/>
		<br/>
		<br/>
		Project Folder:
		<select>
			<option>Project 1</option>
			<option>Project 2</option>
			<option>Project 3</option>
			<option>Project 4</option>
		</select>
		<div style="width:80%; height:500px; overflow:scroll;">
			<div style="width:30%; height:200px; background-color:yellow; float:left;">
			</div>
			<div style="width:30%; height:200px; background-color:red; float:left;">
			</div>
			<div style="width:30%; height:200px; background-color:green; float:left;">
			</div>
		</div>
	</div>
</div>
