<!--  
  -->
<ul id="menu" class="nav nav­pills nav-justified" style="position:fixed; z-index:70">
	<li data-menuanchor="home" class="active"><a href="#home"><img class="logo" src="images\logobnw1.png"/></a></li>
    <li data-menuanchor="portfolio"><a href="#portfolio">Portfolio</a></li>
    <li data-menuanchor="inquiry"><a href="#inquiry">Inquiry</a></li>
    <li data-menuanchor="about"><a href="#about">About</a></li>
    <li data-menuanchor="contact"><a href="#contact">Contact Us</a></li>
	<li>
	<form method="post">
		<li class="navbar-form">
			<input type="text" class="form-control"name="username" placeholder="username" required/>
		</li>
		<li class="navbar-form">
			<input type="password" class="form-control" name="password" placeholder="password" required/></li>
		<li class="navbar-form">
			<button type="submit" class="btn btn-sm btn-default">Log in</button>
		</li>
	</form>
	</li>
</ul>
<div id="fullpage">
	<div class="section" data-anchor="home" style="background-color:cyan;">
		<img src="images/bg.png" class="body-div" style="width:100%;"/>
	</div>
	<div class="section" data-anchor="portfolio" style="background-color:red;">
		<div class="slide"><img src="images/galleryImage/a1.jpg" class="body-div" style="width:100%;"/></div>
		<div class="slide"><img src="images/galleryImage/a2.jpg" class="body-div" style="width:100%;"/></div>
		<div class="slide"><img src="images/galleryImage/a3.jpg" class="body-div" style="width:100%;"/></div>
		<div class="slide"><img src="images/galleryImage/b1.jpg" class="body-div" style="width:100%;"/></div>
		<div class="slide"><img src="images/galleryImage/b2.jpg" class="body-div" style="width:100%;"/></div>
	</div>
	<div class="section" data-anchor="inquiry" style="background-color:green;">
	</div>
	<div class="section" data-anchor="about" style="background-color:blue;">
	</div>
	<div class="section" data-anchor="contact" style="background-color:yellow;">
	</div>
</div>
<script type="text/javascript">
	$(document).ready(function() {
	    $('#fullpage').fullpage({
		    menu: '#menu'
		});
	});
</script>