<ul class="nav nav­pills nav-justified nav-fixed" style="height:100px;">
	<li class="navbar-form" >
		<a href="#portfolio" style="font-color:#fff;font-size:25px;">Admin Login</a>
	</li>
	<li><?php if (isset($invalid)):?>
		<div class="alert alert-danger alert-dismissible" role="alert">
		  <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
		  <strong>Warning!</strong> Invalid username or password!
		</div>
	<?php endif; ?></li>
	<li class="navbar-form">
		<form method="post">
		<input type="text" class="form-control"name="username" placeholder="username" required/>
	</li>
	<li class="navbar-form">
		<input type="password" class="form-control" name="password" placeholder="password" required/>
	</li>
	<li class="navbar-form">
		<button type="submit" class="btn btn-sm btn-default col-sm-8" style="top:10px;">Log in</button>
		</form>
	</li>
</ul>
<div class="section" data-anchor="home">
		<img src="images/bg.png" class="body-div" style="width:100%;"/>
</div>
