<div class="nav-fixed-horizontal fc">
	<center>
		<a href="admin" role="button" class="btn btn-info btn-sm "><span class="glyphicon glyphicon-arrow-left"></span> Back</a></br></br>
		<a href="?logout=1" role="button" class="btn btn-info btn-sm "><span class="glyphicon glyphicon-off"></span>Log Out</a></br>
	</center>
</br>
	<ul class="nav nav-pills">
		<li><a href="branch">List of Projects</a></li>
		<li><a href="messages">Messages</a></li>
		<li class="notif" style="background-color:<?php echo isset($unviewed)?'red':'transparent';?>">
			<a href="requests">Request Notifications</a>
		</li>
		<li><a href="addproject">Add Projects</a></li>
		<li><a href="admingal">Gallery</a></li>
		<li><a href="portfolio">Portfolio</a></li>
	</ul>
</div>
<div class="container col-sm-offset-2">
	<div class="container2">
		<div class="row">
			<div class="col-xs-12 col-md-8">
				<h2 class="pull-left" style="font-family:monospace;"> Welcome Admin!</h2>
			</div>
		</div>
		<div class="row col-sm-11">
				<h2>Messages</h2>
				<div class="row">
					<div class="col-sm-2 col-sm-offset-1">
						<ul class="nav nav-pills nav-justified" style="background-color:#eeffee;">
							<?php if (!empty($projects)){
								foreach ($projects as $key => $project) {
									echo '<li><a href="?code='.$project['code'].'">'.$project['code'].'</a></li>';
								}
							}
							else {
								echo '<li>You have no projects</li>';
							} 
							?>

						</ul>
					</div>
					<div class="col-sm-5">
					<?php if (!empty($projects)): ?>
						<div class="msg-box">
							<?php foreach($messages as $key => $message) {
										echo $message['username'].': '.$message['content'].'<br/>';
									}
							?>
						</div>
						<div style="padding-top:10px;">
							<textarea name="content" class=" form-control" rows="2" cols="15" style="font-size: 10pt; font-family: Arial;"></textarea></br>
							<button class="send btn btn-warning">Send</button>
						</div>
					<?php endif; ?>
					</div>
						<div class="col-sm-4">
								<h4>Choose a photo to upload</h4>
								<div class="success alert alert-success alert-dismissible" role="alert">
								  <button type="button" class="close" data-dismiss="alert">
								  	<span aria-hidden="true">&times;</span>
								  	<span class="sr-only">Close</span></button>
								  <strong>Success!</strong> You've successfully uploaded an item!
								</div>
							<form method="POST" enctype="multipart/form-data">
								<div class="image error alert alert-danger alert-dismissible" role="alert">
								  <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
								  <strong>Warning!</strong> Please choose a file to upload!
								</div>
								<div class="invalid-image error alert alert-danger alert-dismissible" role="alert">
								  <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
								  <strong>Warning!</strong>The file chosen is not an image
								</div>
								<img class="col-sm-offset-3 picture-inner" style="display: none;"/></br>
								<div class=" col-sm-12">
										<div class="col-sm-offset-3">
												<div class=" col-sm-12">
													<input type="file" name="file" class="btn-file"/></br>
													<button class="pull-left btn btn-lg btn-danger col-sm-12 submit" style="margin-right:30px">Upload</button>
												</div>
										</div>
								</div>
							</form>
						</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	function comet() {
		$.ajax({
			type : 'GET',
			url  : 'read',
			data: {code : "<?php echo $code; ?>"},
			async : true,
			cache : false,
			success : function(data) {
						var json = eval("("+data+")");
						$(".msg-box").html(json['msg']);
						setTimeout('comet()', 1000);
			},
			error : function(XMLHttpRequest, textstatus, error) { 
						alert(error);
						setTimeout('comet()', 15000);
			}		
		});
	}
	$(function() {
		comet();
	});
	jQuery(function($) {
		$(".send").on("click", function() {
			var msg ="<?php echo $user['username'].': ';?>"+$(this).parent().children("textarea").val()+"<br/>";
			$.ajax({
				type: "POST",
				url: "messages",
				data: {code : "<?php echo $code; ?>", message : $(this).parent().children("textarea").val()}
			});
			$.ajax({
				type : 'GET',
				url  : 'write',
				data: {msg: msg, code : "<?php echo $code; ?>"},
				async : true,
				cache : false
			});
			$(this).parent().children("textarea").val("");
		});
	});

	jQuery(function($) {
		$(".submit").on("click", function(e) {
			e.preventDefault();
			var error = false;
			$(".error").hide();
			if ($("input[type='file']")[0].files.length == 0) {
				$(".image").show();
				error = true;
				// alert('hey');
			}
			if (!error) {
				var fd = new FormData();
				fd.append("image",$(this).parent().find("input[type='file']")[0].files[0]);
				$(".success").show();
				$(".picture-inner").hide();
				$(this).replaceWith($(this).val("").clone(true));
				$.ajax({
					type: "POST",
					url: "portfolio",
					data: fd,
		            processData: false,
		            contentType: false
				});
			}
		});
		$("input[type='file']").on("change", function() {
			$(".success").hide();
			if ($(this)[0].files[0].type.search(/jpeg|png|gif/) == -1) {
				$(".invalid-image").show();		
				$(this).replaceWith($(this).val("").clone(true));
				$(".picture-inner").hide();
			}
			else {
				var reader = new FileReader();
	            reader.onload = function (e) {
	                $(".picture-inner").attr("src", e.target.result).css("display","inline");
	            };
	            reader.readAsDataURL($(this)[0].files[0]);
				$(".invalid-image").hide();		
			}
		});
	});
</script>
