<div>
	<div class="clearfix" style="position:fixed;z-index:70;height:70px;width:100%;background-color:black;">
		<h1 class="pull-left header-name">Hi Admin</h1>
	
	</div>
	<div style="position:fixed;z-index:70;height:100%;width:20em;background-color:grey;margin-top:70px">
		<ul class="project">
			<li>List of Projects</li>
			<li>Messages</lu>
			<li>Request Notif</li>
			<li>Add Project</li>
		</ul>
	</div>
	<div class="col-sm-offset-3" style="position:fixed;height:30em;width:40em;background-color:cornflowerblue;margin-top:8em;border-radius:10px;">
		<div style="height:30em;width:40em;background-color:grey;border-radius:10px">
		</div>
		<div style="height:80px;width:40em;background-color:grey;;margin-top:3em;border-radius:10px">
			<button class="button-send pull-right">Send
			</button>
		</div>
	</div>
	<div class="col-sm-offset-9" style="position:fixed;height:39em;width:20em;background-color:cornflowerblue;margin-top:8em">
		<div style="height:30em;width:20em;background-color:grey;border-radius:10px">
		</div>
		<div style="height:10em;width:20em;background-color:cornflowerblue;margin-top:2em;">
			<button class="button-upload">Upload</button>
		</div>
	</div>
</div>