<ul id="menu" class="nav nav­pills nav-justified nav-fixed">
		<li data-menuanchor="home" class="active"><a href="#home"><img class="logo" src="images\logobnw1.png"/></a></li>
   	 	<li><a href="projects">Projects</a></li>
		<li><a href="gallery">Gallery</a></li>
		<li><a href="customer">Messages</a></li>
		<li><a href="billing">Billing</a></li>
		<li><button class="btn btn-info">Notifications</button></a>
		</li>
		<li><a href="?logout=1" role="button" class="btn btn-info"><span class="glyphicon glyphicon-off"></span></a></li>
		<li></li>
</ul>
<div class="container">
	<div class="container2 fc">
		<div class="row">
			<div class="col-xs-12 col-md-8">
				<h2 class="pull-left" style="font-family:monospace;"> Welcome User!</h2>
			</div>
		</div>
		<div class="row col-sm-11">
				<center><h3>Projects</h3></center>
					<button type="submit" class="btn btn-info btn-sm col-sm-2 pull-right">Add a project</button>
				<div class="row">
					<div class="col-sm-4 proj-border">
							
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
	function comet() {
		$.ajax({
			type : 'GET',
			url  : 'read',
			data: {code : "<?php echo $code; ?>"},
			async : true,
			cache : false,
			success : function(data) {
						var json = eval("("+data+")");
						$(".msg-box").html(json['msg']);
						setTimeout('comet()', 1000);
			},
			error : function(XMLHttpRequest, textstatus, error) { 
						alert(error);
						setTimeout('comet()', 15000);
			}		
		});
	}
	$(function() {
		comet();
	});
	jQuery(function($) {
		$(".send").on("click", function() {
			var msg ="<?php echo $user['username'].': ';?>"+$(this).parent().children("textarea").val()+"<br/>";
			$.ajax({
				type: "POST",
				url: "messages",
				data: {code : "<?php echo $code; ?>", message : $(this).parent().children("textarea").val()}
			});
			$.ajax({
				type : 'GET',
				url  : 'write',
				data: {msg: msg, code : "<?php echo $code; ?>"},
				async : true,
				cache : false
			});
			$(this).parent().children("textarea").val("");
		});
	});

	jQuery(function($) {
		$(".submit").on("click", function(e) {
			e.preventDefault();
			var error = false;
			$(".error").hide();
			if ($("input[type='file']")[0].files.length == 0) {
				$(".image").show();
				error = true;
				// alert('hey');
			}
			if (!error) {
				var fd = new FormData();
				fd.append("image",$(this).parent().find("input[type='file']")[0].files[0]);
				$(".success").show();
				$(".picture-inner").hide();
				$(this).replaceWith($(this).val("").clone(true));
				$.ajax({
					type: "POST",
					url: "portfolio",
					data: fd,
		            processData: false,
		            contentType: false
				});
			}
		});
		$("input[type='file']").on("change", function() {
			$(".success").hide();
			if ($(this)[0].files[0].type.search(/jpeg|png|gif/) == -1) {
				$(".invalid-image").show();		
				$(this).replaceWith($(this).val("").clone(true));
				$(".picture-inner").hide();
			}
			else {
				var reader = new FileReader();
	            reader.onload = function (e) {
	                $(".picture-inner").attr("src", e.target.result).css("display","inline");
	            };
	            reader.readAsDataURL($(this)[0].files[0]);
				$(".invalid-image").hide();		
			}
		});
	});
</script>
