<div class="container">
	<div class="row container2  msg">
			<h1>Registration</h1>
		<div class="registration">
			<form method="POST">
				<div class="col-sm-4">
					<input type="text" class="form-control" name="lname" placeholder="last name" required/><br/>
					<input type="text" class="form-control" name="fname" placeholder="first name" required/><br/>
					<input type="text" class="form-control" name="mname" placeholder="middle name" required/><br/>
				</div>
				<div class="col-sm-4">
						<input type="text" class="form-control" name="address" placeholder="address" required/><br/>
						<input type="email" class="form-control" name="email" placeholder="email" required/><br/>
						<input type="text" class="form-control" name="contact" placeholder="contact no." required/><br/>
				</div>
				<div class="col-sm-4">
					<input type="text" class="form-control" name="username" placeholder="username" required/></br>
					<input type="password" class="form-control" name="password" placeholder="password" required/><br/>
					<input type="password" class="form-control" name="confirm" placeholder="confirm password" required/><br/>
					<input type="text" class="form-control" name="code" placeholder="project code" required/><br/>
				</div>
						<button type="submit" class="btn btn-info btn-lg pull-right">Submit</button>
			</form>
		</div>
	</div>
</div>