<form method="POST">
<input type="text" name="username" placeholder="username" required/><br/>
<input type="password" name="password" placeholder="password" required/><br/>
<input type="password" name="confirm" placeholder="confirm password" required/><br/>
<input type="text" name="lname" placeholder="last name" required/><br/>
<input type="text" name="fname" placeholder="first name" required/><br/>
<input type="text" name="mname" placeholder="middle name" required/><br/>
<input type="text" name="address" placeholder="address" required/><br/>
<input type="email" name="email" placeholder="email" required/><br/>
<input type="text" name="contact" placeholder="contact no." required/><br/>
<input type="text" name="code" placeholder="project code" required/><br/>
<button type="submit">Submit</button>
</form>