<div class="nav-fixed-horizontal fc">
	<center>
		<a href="admin" role="button" class="btn btn-info btn-sm "><span class="glyphicon glyphicon-arrow-left"></span> Back</a></br></br>
		<a href="?logout=1" role="button" class="btn btn-info btn-sm "><span class="glyphicon glyphicon-off"></span>Log Out</a></br>
	</center>
</br>
	<ul class="nav nav-pills">
		<li><a href="branch">List of Projects</a></li>
		<li><a href="messages">Messages</a></li>
		<li class="notif" style="background-color:<?php echo isset($unviewed)?'red':'transparent';?>">
			<a href="requests">Request Notifications</a>
		</li>
		<li><a href="addproject">Add Projects</a></li>
		<li><a href="portfolio">Portfolio</a></li>
	</ul>
</div>
<div class="container col-sm-offset-2">
	<div class="container2">
		<div class="row">
			<div class="col-xs-12 col-md-8">
				<h2 class="pull-left" style="font-family:monospace;"> Welcome Admin!</h2>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-9 col-sm-offset-1 request-box">
				<?php foreach ($requests as $key => $request): ?>
					<div class="panel-group" id="accordion">
					  <div class="panel panel-default">
					    <div class="panel-heading">
					      <h4 class="panel-title">
					      	<b>Sender:</b> <?php echo $request['sender_name']; ?>
					      </h4>
					    </div>
					    <div id="collapseOne" class="panel-collapse collapse in">
					      <div class="panel-body">
								<b>E-mail:</b><?php echo $request['sender_email']; ?>
							</br>

								<b>Request:</b>
								<p><?php echo $request['content']; ?></p>
					      </div>
					    </div>
					  </div>
					 </div>
				<?php endforeach ?>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
</script>