<div class="container">
	<div class="container2">
		<div class="row">
			<div class="col-xs-12 col-md-8">
				<h2 class="pull-left" style="font-family:monospace;"> Welcome Admin!</h2>
			</div>
		</div>
		<div class="row">
			<div class="col-sm-2 ">
				<center>
				<a href="/admin" role="button" class="btn btn-info btn-lg btn-margin col-sm-12"><span class="glyphicon glyphicon-off"></span> Back</a>
				<a href="?logout=1" role="button" class="btn btn-info btn-lg btn-margin col-sm-12"><span class="glyphicon glyphicon-off"></span> Log Out</a>
				</center>
			</div>
			<div class="col-sm-9 col-sm-offset-1 msg-box">
				<?php foreach ($requests as $key => $request): ?>
					<div class="panel-group" id="accordion">
					  <div class="panel panel-default">
					    <div class="panel-heading">
					      <h4 class="panel-title">
					      	<b>Sender:</b> <?php echo $request['sender_name']; ?>
					      </h4>
					    </div>
					    <div id="collapseOne" class="panel-collapse collapse in">
					      <div class="panel-body">
								<b>E-mail:</b><?php echo $request['sender_email']; ?>
							</br>

								<b>Request:</b>
								<p><?php echo $request['content']; ?></p>
					      </div>
					    </div>
					  </div>
					 </div>
				<?php endforeach ?>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
</script>