<div id="fullpage">
	<div class="section">
	    <div class="slide" data-anchor="slide1" style="background-color:red"> Slide 1 </div>
	    <div class="slide" data-anchor="slide2" style="background-color:blue"> Slide 2 </div>
	    <div class="slide" data-anchor="slide3" style="background-color:green"> Slide 3 </div>
	    <div class="slide" data-anchor="slide4" style="background-color:yellow"> Slide 4 </div>
	</div>
    <div class="section">Some section</div>
    <div class="section">Some section</div>
    <div class="section">Some section</div>
    <div class="section">Some section</div>
</div>
<button class="btn btn-default">TEST</button>
<script type="text/javascript">
	$(document).ready(function() {
	    $('#fullpage').fullpage();
	});
</script>